pertence(noruegues,casa1).
pertence(leite,casa3).
pertence(azul,casa2).
pertence(verde,casa4).
pertence(branco,casa5).
pertence(cafe,casa4).
pertence(vermelho,casa3).
pertence(ingles,casa3).
pertence(amarelo,casa1).
pertence(dunhill,casa1).
pertence(cavalos,casa2).
pertence(agua,casa1).
pertence(blends,casa2).
pertence(gato,casa1).
pertence(cerveja,casa5).
pertence(bluemaster,casa5).
pertence(sueco,casa5).
pertence(cachorro,casa5).
pertence(dinamarques,casa2).
pertence(cha,casa2).
pertence(alemao,casa4).
pertence(prince,casa4).
pertence(peixes,casa4).
pertence(pallmall,casa3).
pertence(passaros,casa3).
